name: Common

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
permissions:
  contents: write

jobs:
  clang-format-checking:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: RafikFarhad/clang-format-github-action@v3
      with:
        sources: "include/**/*.h,src/**/*.h,src/**/*.c,tests/**/*.h,\
          tests/**/*.c,samples/**/*.h, samples/**/*.c"
        style: file

  doxygen-run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup
      run: |
        sudo apt update
        sudo apt-get install doxygen
        sudo apt-get install graphviz
    - name: Generate docs
      run: tools/picky.sh make docs
    - uses: actions/upload-artifact@v4
      with:
        name: doxygen-output
        path: docs/

  deploy:
    runs-on: ubuntu-latest
    needs: clang-format-checking
    needs: doxygen-run
    needs: all-good-default
    needs: all-good-iso
    needs: coverage-posix-on-unix
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Download artifact
    - uses: actions/download-artifact@v4
      with:
        name: doxygen-output
        path: docs
    - name: Deploy Doxygen Docs
      uses: AgarwalSaurav/ghaction-doxygen-ghpages@release/v2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        folder: docs/html
