name: Common

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  clang-format-checking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: RafikFarhad/clang-format-github-action@v3
        with:
          sources: "include/**/*.h,src/**/*.h,src/**/*.c,tests/**/*.h,\
            tests/**/*.c,samples/**/*.h, samples/**/*.c"
          style: file

  doxygen-output:
    runs-on: ubuntu-latest
    steps:
      - uses: mattnotmitt/doxygen-action@v1.9.5
        with:
          working-directory: '/home/runner/work/cantil/cantil'
