name: Common

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  clang-format-checking:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: RafikFarhad/clang-format-github-action@v3
      with:
        sources: "include/**/*.h,src/**/*.h,src/**/*.c,tests/**/*.h,\
          tests/**/*.c,samples/**/*.h, samples/**/*.c"
        style: file

  doxygen-run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup
      run: |
        sudo apt update
        sudo apt-get install doxygen
        sudo apt-get install graphviz
    - name: Generate docs
      run: tools/picky.sh make docs
    - uses: actions/upload-artifact@v4
      with:
        name: doxygen-output
        path: docs/
