name: Default

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  verify-unix:
    name: Verify for ubuntu/macos
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v4
    - name: Setup
      run: |
        sudo apt update
        sudo apt-get install valgrind
    - name: Build cantil
      run: tools/picky.sh make cantil-default
    - name: Build tests
      run: tools/picky.sh make all-default
    - name: Run tests
      run: make check-default

  verify-win32:
    name: Verify for windows
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup
      run: |
        python -m pip install pyyaml
    - name: Build cantil
      run: tools/picky.sh make cantil-default
    - name: Build tests
      run: tools/picky.sh make all-default
    - name: Run tests
      run: tools/picky.sh make check-default
