name: Default

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  verify-unix:
    name: Verify
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v4
    - name: Setup
      run: |
        sudo apt update
        sudo apt-get install valgrind
    - name: Build
      run: make all
    - name: Run tests
      run: make check

  verify-win32:
    name: Verify
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup
      run: |
        python -m pip install pyyaml
    - name: Build
      run: make all
    - name: Run tests
      run: make check
