name: Default CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  default-unix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v4
    - name: check
      run:
        sudo apt update
        sudo apt-get install valgrind
        make check

  default-win32:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: check
      run:
        make check
