name: ISO CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
        make all-iso

  test-unix:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      run: |
        sudo apt update
        sudo apt-get install valgrind
        make check-iso

  test-win32:
    needs: build
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: check
      run: |
        python -m pip install pyyaml
        make check-iso

  coverage:
    needs: test-unix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v4
    - name: Checkout code
      run: |
        make coverage-iso
    - name: Setup LCOV
      uses: hrishikesh-kadam/setup-lcov@v1
    - name: Report code coverage
      uses: zgosalvez/github-actions-report-lcov@v4
      with:
        coverage-files: build-iso/tests/reports.d/coverage.info
        minimum-coverage: 100
        artifact-name: code-coverage-report
