name: ISO CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  iso-unix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v4
    - name: check
      run: |
        sudo apt update
        sudo apt-get install valgrind
        make check-iso

  iso-win32:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: check
      run: |
        python -m pip install pyyaml
        make check-iso
