name: ISO

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  verify-unix:
    name: Verify Unix build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    steps:
    - name: Setup
    - uses: actions/checkout@v4
      run: |
        sudo apt update
        sudo apt-get install valgrind
    - name: Build
      run: make all-iso
    - name: Run tests
      run: make check-iso
    - name: Checkout code
      run: make coverage-iso
    - name: Setup LCOV
      uses: hrishikesh-kadam/setup-lcov@v1
    - name: Report code coverage
      uses: zgosalvez/github-actions-report-lcov@v4
      with:
        coverage-files: build-iso/tests/reports.d/coverage.info
        minimum-coverage: 100
        artifact-name: code-coverage-report

  verify-win32:
    name: Verify Windows build
    runs-on: windows-latest
    steps:
    - name: Setup
    - uses: actions/checkout@v4
      run: |
        python -m pip install pyyaml
    - name: Build
      run: make all-iso
    - name: Run tests
      run: make check-iso
