name: ISO

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  verify-unix:
    name: Verify for ubuntu/macos
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v4
    - name: Setup
      run: |
        sudo apt update
        sudo apt-get install valgrind
        sudo apt-get install lcov
    - name: Build cantil
      run: tools/picky.sh make cantil-iso
    - name: Clone Unity
      run: make unity-iso
    - name: Build tests
      run: tools/picky.sh make all-iso
    - name: Run tests
      run: tools/picky.sh make check-iso
    - name: Checkout code
      run: tools/picky.sh make coverage-iso
    - name: Setup LCOV
      uses: hrishikesh-kadam/setup-lcov@v1
    - name: Report code coverage
      uses: zgosalvez/github-actions-report-lcov@v4
      with:
        coverage-files: build-iso/tests/reports.d/coverage.info
        minimum-coverage: 100
    - uses: actions/upload-artifact@v4
      with:
        name: iso-${{ matrix.platform }}-reports
        path: build-iso/tests/reports.d/

  verify-win32:
    name: Verify for windows
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup
      run: |
        python -m pip install pyyaml
    - name: Build cantil
      run: tools/picky.sh make cantil-iso
    - name: Clone Unity
      run: make unity-default
    - name: Build tests
      run: tools/picky.sh make all-iso
    - name: Run tests
      run: tools/picky.sh make check-iso
