name: POSIX

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-posix-on-unix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    steps:
    - name: Checkout
    - uses: actions/checkout@v4
    - name: Build cantil
      run: tools/picky.sh make cantil-posix
    - name: Upload artifact
    - uses: actions/upload-artifact@v4
      with:
        name: build-posix-on-${{ matrix.platform }}-output
        path: build-posix/

  check-posix-on-unix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    needs: build-posix-on-unix
    steps:
    - name: Checkout
    - uses: actions/checkout@v4
    - name: Setup
      run: |
        sudo apt update
        sudo apt-get install valgrind
        sudo apt-get install lcov
    - name: Clone Unity
      run: make unity-posix
    - name: Build tests
      run: tools/picky.sh make all-posix
    - name: Run tests
      run: tools/picky.sh make check-posix
    - name: Checkout code
      run: tools/picky.sh make coverage-posix
    - name: Upload artifact
    - uses: actions/upload-artifact@v4
      with:
        name: check-posix-on-${{ matrix.platform }}-output
        path: build-posix/

  coverage-posix-on-unix:
    runs-on: ubuntu-latest
    needs: check-posix-on-unix
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    steps:
    - name: Checkout
    - uses: actions/checkout@v4
    - name: Download artifact
    - uses: actions/download-artifact@v4
      with:
        name: check-posix-on-${{ matrix.platform }}-output
        path: build-posix/
    - name: Setup LCOV
      uses: hrishikesh-kadam/setup-lcov@v1
    - name: Report code coverage
      uses: zgosalvez/github-actions-report-lcov@v4
      with:
        coverage-files: build-posix/tests/reports.d/coverage.info
        minimum-coverage: 100
