name: POSIX

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  verify:
    name: Verify for ubuntu/macos
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - 'ubuntu-latest'
          - 'macos-latest'
    steps:
    - uses: actions/checkout@v4
    - name: Setup
      run: |
        sudo apt update
        sudo apt-get install valgrind
        sudo apt-get install lcov
    - name: Build cantil
      run: tools/picky.sh make cantil-posix
    - name: Clone Unity
      run: make Unity
    - name: Build tests
      run: tools/picky.sh make all-posix
    - name: Run tests
      run: tools/picky.sh make check-posix
    - name: Checkout code
      run: tools/picky.sh make coverage-posix
    - name: Setup LCOV
      uses: hrishikesh-kadam/setup-lcov@v1
    - name: Report code coverage
      uses: zgosalvez/github-actions-report-lcov@v4
      with:
        coverage-files: build-posix/tests/reports.d/coverage.info
        minimum-coverage: 100
    - uses: actions/upload-artifact@v4
      with:
        name: posix-${{ runner.os }}-reports
        path: build-posix/tests/reports.d/
