name: Release

on:
  workflow_run:
    workflows: [ "Default", "ISO", "Ready" ]
    branches: [ "main" ]
    types:
      - completed

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dawidd6/action-download-artifact@v11
      with:
        workflow: ready.yaml
        name: doxygen-output
        path: docs
    - name: Deploy Doxygen Docs
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/html
