name: Release

on:
  workflow_run:
    workflows: [ "Ready" ]
    branches: [ "main" ]
    types:
      - completed

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dawidd6/action-download-artifact@v11
      with:
        workflow: ready.yaml
        name: doxygen-output
        path: public
        branch: ${BRANCH_NAME}
    - name: Deploy Doxygen Docs
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: public/html
