name: Release

on:
  workflow_run:
    workflows: ["Common", "Default", "ISO", "POSIX"]
    branches: [main]
    types:
      - completed
permissions:
  contents: write

jobs:
  doxygen-run:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - uses: actions/checkout@v4
    - name: Setup
      run: |
        sudo apt update
        sudo apt-get install doxygen
        sudo apt-get install graphviz
    - name: Generate docs
      run: tools/picky.sh make docs
    - uses: actions/upload-artifact@v4
      with:
        name: doxygen-output
        path: docs/

  deploy:
    runs-on: ubuntu-latest
    needs: doxygen-run
    steps:
    - uses: actions/checkout@v4
    - uses: actions/download-artifact@v4
      with:
        name: doxygen-output
        path: docs
    - name: Deploy Doxygen Docs
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/html
